qnd041app/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

qnd041app/usuarios/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


from django.urls import path
from . import views
from .views import ProfileDetailView

urlpatterns = [
    # otras rutas...
    
]



app_name = 'usuarios'

urlpatterns = [
    # previous login view
    
    path('', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('activar/<uidb64>/<token>/', views.activar_cuenta, name='activar_cuenta'),
    
    path('dashboard', views.dashboard, name='dashboard'),
    path('settings', views.settings, name='settings'),
    path("dashboard/micro/", views.dashboard_micro, name="dashboard_micro"),
    path("dashboard/pequena/", views.dashboard_pequena, name="dashboard_pequena"),
    path("dashboard/mediana/", views.dashboard_mediana, name="dashboard_mediana"),
    path("dashboard/enterprise/", views.dashboard_enterprise, name="dashboard_enterprise"),
    path("dashboard/user/", views.dashboard_pather, name="dashboard_pather"),

    path(
        'politicas-terminos/',
        views.politicas_terminos,
        name='politicas_terminos'
    ),

    path("configuraciones/perfil_usuario", ProfileDetailView.as_view(), name="profile_view"),
    path("configuraciones/perfil_usuario_editar/", views.editar_perfil, name="editar_perfil"),

    path("preview/login-email/", views.preview_login_notification_email, name="preview_login_email"),
    path("preview/email/password-reset/", views.preview_password_reset_email, name="preview_password_reset_email"),
    path('preview/activation-email/', views.preview_account_activation_email, name='preview_activation_email'),



    path('recuperar/', views.password_reset_request, name='password_reset_request'),
    path('restablecer/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
     
  
    path('perfil_de_usuario/', views.profile_edit_view , name='perfil'),

    path('Citas/', views.gestionar_citas_view, name='citas'),
    path('citas/<int:cita_id>/cancelar/', views.cancelar_cita_view, name='cancelar_cita'),
    path('citas/<int:cita_id>/editar/', views.editar_cita_view, name='editar_cita'),

    path('citas/nueva/', views.agendar_cita, name='agendar_cita'),
    path('citas/success/', views.cita_success, name='cita_success'),  

    path('calendario/', views.citas_agendadas_total , name='citas_total'),
    path('calendario_total/', views.citas_record , name='citas_record'),
    path('citas/ver/<int:pk>/', views.ver_cita, name='ver_cita'),
    path('cita/<int:pk>/confirmar/', views.confirmar_cita, name='confirmar_cita'),
    path('cita/<int:pk>/cancelar/', views.cancelar_cita, name='cancelar_cita'),


    path('tareas/nuevas/', views.tareas_list, name='lista_tareas'),
    path('tareas/asignadas/', views.tareas_asignadas, name='tareas_asignadas'),
    path('tareas/realizadas/', views.tareas_realizadas, name='tareas_realizadas'),
    path('tareas/<int:pk>/marcar_realizada/', views.marcar_tarea_realizada, name='marcar_tarea_realizada'),


    path('tarea/<int:pk>/', views.ver_tarea, name='ver_tarea'),
    path('tarea/<int:pk>/interactiva/', views.ver_tarea_interactiva, name='ver_tarea_interactiva'),

    path('pagos/', views.lista_pagos, name='lista_pagos'),
    path('pagos/pendientes/', views.pagos_pendientes_view, name='pagos_pendientes'),
    path('pagos/adeudados/', views.pagos_vencidos_view, name='pagos_vencidos'),

    path('pagos/<int:pk>/', views.ver_pago, name='ver_pago'),
    path('pagos/<int:pk>/subir-comprobante/', views.subir_comprobante_pago, name='subir_comprobante_pago'),

    path('certificados/', views.vista_certificados, name='vista_certificados'),



    path('inbox/', views.inbox_view , name='inbox'),
    path('inbox_total/', views.inbox_record , name='inbox_total'),
    path('mensajes/ver/<int:pk>/', views.ver_mensaje, name='ver_mensaje'),
    path('nuevo_mensaje/', views.enviar_mensaje, name='enviar_mensaje'),
    path('Confirmacion/', views.msj_success, name='success'),
    path('configuracion_de_usuario/', views.config_view , name='configuraciones'),

    path('tareas/', views.TareaListView.as_view(), name='tarea_list'),
    path('tareas/<int:pk>/', views.TareaDetailView.as_view(), name='tarea_detail'),

    path('actividades/', views.ActividadListView.as_view(), name='actividad_list'),
    path('actividades/<int:pk>/', views.ActividadDetailView.as_view(), name='actividad_detail'),

    path('terapias/', views.TerapiaListView.as_view(), name='terapia_list'),
    path('terapias/<int:pk>/', views.TerapiaDetailView.as_view(), name='terapia_detail'),

    path('asistidas/', views.CitasAsistidasListView.as_view(), name='citas_asistidas'),
    path('no-asistidas/', views.CitasNoAsistidasListView.as_view(), name='citas_no_asistidas'),
    path('pendientes/', views.CitasPendientesListView.as_view(), name='citas_pendientes'),
    path('<int:pk>/', views.CitaDetailView.as_view(), name='detalle'),

   # path('actividades_espacio_publico/', views.user_activity_login, name='login_activity'),
   # path('Reserva_de_espacio_publico/', views.user_activity_login, name='login_activity'),
  
   # path('dashboard', views.dashboard, name='dashboard'),
   # path('perfil_de_usuario/', views.profile_view , name='perfil'),
   # path('configuracion_de_usuario/', views.config_view , name='configuraciones'),
  
    # change password urls

    # alternative way to include authentication views
    # path('', include('django.contrib.auth.urls')),
   # path('registro_para_postulacion_a_convocatorias/', views.register, name='register'),
   # path('registro_para_proponer_actividades_culturales__espacios_publicos/', views.activity_register, name='activity_register'),
   # path('registro_para_uso_espacio_publico/', views.register_public, name='register_public'),
   # path('edit/', views.edit, name='edit'),
  #  path('edit_contacto_1/', views.edit_contact, name='edit_contact1'),
 #   path('edit_contacto_2/', views.edit_contact2, name='edit_contact2'),
  #  path('edit_contacto_3/', views.edit_contact3, name='edit_contact3'),
 #   path('edit_contacto_4/', views.edit_contact4, name='edit_contact4'),
  #  path('Actividad_Cultural/', views.edit_activity, name='edit_activity'),
 #   path('edit_legal1/', views.edit_legal, name='edit_legal'),
  #  path('edit_legal2/', views.edit_legal2, name='edit_legal2'),
 #   path('Declaratoria/', views.edit_declaratoria, name='edit_declaratoria'),
 #   path('confirmacion/', views.confirmacion, name='confirmacion'),
#    path('privacy/', views.privacy_policy_view , name='privacy_policy'),
#    path('terms/', views.terms_of_use_view , name='terms_of_use'),
 #   path('Activityprivacy/', views.activity_privacy_policy_view , name='activity_privacy_policy'),
#    path('Activityterms/', views.activity_terms_of_use_view , name='activity_terms_of_use'),
#    path('inicio_crear_convocatoria/', views.manual_crear_convocatoria, name='inicio_crear_convocatoria'),
#    path('inicio_editar_convocatoria/', views.manual_editar_convocatoria, name='inicio_editar_convocatoria'),
 #   path('inicio_Mis_convocatoria/', views.manual_mis_convocatoria, name='inicio_mis_convocatoria'),
 #   path('inicio_Inscripciones/', views.manual_inscripcion, name='inicio_inscripcion'),
   # path('inicio_postulacion/', views.manual_postulation, name='inicio_postulation'),  # Corrected name
 #   path('inicio_Mis_postulaciones/', views.manual_mis_postulaciones, name='inicio_mis_postulaciones'),
 #   path('inicio_crear_Proyecto/', views.manual_crear_proyecto, name='inicio_crear_proyecto'),
 #   path('inicio_editar_Proyecto/', views.manual_editar_proyecto, name='inicio_editar_proyecto'),
#    path('inicio_Mis_Proyecto/', views.manual_mis_proyectos, name='inicio_mis_proyectos'),

   # path('admin/profile/<int:profile_id>/pdf/', views.admin_profile_pdf, name='admin_profile_pdf'),
]

qnd041app/usuarios/templates/usuarios/edit_profile/confirmacion.html
{% extends "base_dash.html" %}
{% load wagtailimages_tags wagtailcore_tags %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}
{% load widget_tweaks %}
{% load static %}
{% load menu_tags %}



{% block content %}
<div class="page-content-wrapper">
  <!-- start page content-->
  <div class="page-content">

    <!--start breadcrumb-->
    <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
      <div class="breadcrumb-title pe-3"><ion-icon name="card"></ion-icon> Inscripción</div>
      <div class="ps-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb mb-0 p-0 align-items-center">
            <li class="breadcrumb-item"><a href="javascript:;">
              <ion-icon name="school"></ion-icon>
              </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">{% block title %} Declaratoria {% endblock %}</li>
          </ol>
        </nav>
      </div>

    </div>

    <h6 class="text-uppercase">Proceso de Inscripción para el uso del sistema de gestión de fomento y actividades culturales en espacios públicos.</h6>
    <hr>
  <div id="stepper1" class="bs-stepper">
    <div class="card">
      
      <div class="card-header">
        <div class="d-lg-flex flex-lg-row align-items-lg-center justify-content-lg-between" role="tablist">
          <div class="step" data-target="#test-nl-1">
          <div class="step-trigger" role="tab" id="stepper1trigger1" aria-controls="test-nl-1">
            <div class="bs-stepper-circle"><i class='bx bx-user fs-4'></i></div>
            <div class="">
              <h5 class="mb-0 steper-title">Perfil de usuario</h5>
              <p class="mb-0 steper-sub-title">Información de Perfil del usuario</p>
            </div>
          </div>
          </div>
          <div class="bs-stepper-line"></div>
          <div class="step" data-target="#test-nl-2">
            <div class="step-trigger" role="tab" id="stepper2trigger2" aria-controls="test-nl-2">
            <div class="bs-stepper-circle"><ion-icon name="paper-plane-outline"></ion-icon></div>
            <div class="">
              <h5 class="mb-0 steper-title">Contacto de usuario</h5>
              <p class="mb-0 steper-sub-title">Información de contacto del usuario</p>
            </div>
            </div>
          </div>
          <div class="bs-stepper-line"></div>
          <div class="step" data-target="#test-nl-3">
            <div class="step-trigger" role="tab" id="stepper2trigger3" aria-controls="test-nl-3">
            <div class="bs-stepper-circle"><i class='bx bxs-graduation fs-4'></i></div>
            <div class="">
              <h5 class="mb-0 steper-title">Personería Jurídica</h5>
              <p class="mb-0 steper-sub-title">Información de personería jurídica</p>
            </div>
            </div>
          </div>
          <div class="bs-stepper-line"></div>
            <div class="step" data-target="#test-nl-4">
              <div class="step-trigger" role="tab" id="stepper2trigger4" aria-controls="test-nl-4">
              <div class="bs-stepper-circle"><i class='bx bx-play fs-4'></i></div>
              <div class="">
                <h5 class="mb-0 steper-title">Actividad Cultural</h5>
                <p class="mb-0 steper-sub-title">Información actividad cultural del usuario</p>
              </div>
              </div>
            </div>
        </div>
      </div>
      <div class="card-body">
      
      <div class="bs-stepper-content">

        <div class="card">
            <div class="card-body text-center">
              <h2 class="h4 pb-3">Gracias, <strong>{{ profile.user.get_full_name }}.</strong></h2>
              <p class="fs-sm mb-2">Por realizar el proceso de  inscribición en nuestra plataforma de gestión cultural de la Secretaría de Cultura! Nos complace darle la bienvenida a nuestra comunidad dedicada al fomento y promoción de la cultura en el Municipio del Distrito Metropolitano de Quito.</p>
              <p class="fs-sm mb-2">Ahora que has completado tu registro, tienes acceso completo a nuestra plataforma. Puedes explorar las diversas convocatorias vigentes accediendo a los siguientes enlaces. Además, puedes crear y presentar proyectos para postularte a las diferentes convocatorias y también para proponer actividades culturales que enriquezcan nuestra comunidad.

                Estamos emocionados de tenerte a bordo y esperamos colaborar contigo en la realización de proyectos culturales significativos para nuestra ciudad.
                
                ¡Bienvenido y gracias por formar parte de nuestra comunidad cultural!
              </p>
              <p class="fs-sm">
              </p>
              <a class="btn btn-primary mt-3" href="{% url 'usuarios:dashboard' %}">Volver al Inicio</a>
            </div>
          </div>

      
      </div>
       
      </div>
     </div>
  </div>


    
  </div>





  
{% endblock %}

<h1>Edit your account</h1>
  <p>You can edit your account using the following form:</p>
  <form action="." method="post" enctype="multipart/form-data">
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Save changes"></p>
  </form>

qnd041app/usuarios/templates/usuarios/edit_profile/datepicker_widget.html
{% load wagtailimages_tags wagtailcore_tags %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}
{% load widget_tweaks %}
{% load static %}
{% load menu_tags %}



<div class="mb-3">
<input type="text" class="form-control datepicker" />
</div>

qnd041app/usuarios/templates/usuarios/edit_profile/edit.html
{% extends "base_dash.html" %}
{% load wagtailimages_tags wagtailcore_tags %}
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}
{% load widget_tweaks %}
{% load static %}
{% load menu_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}





{% block content %}

<div class="page-content-wrapper">
  <!-- start page content-->
  <div class="page-content">

    <!--start breadcrumb-->
    <!--start breadcrumb-->
    <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
      <div class="breadcrumb-title pe-3"><ion-icon name="card"></ion-icon> Inscripción</div>
      <div class="ps-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb mb-0 p-0 align-items-center">
            <li class="breadcrumb-item"><a href="javascript:;">
              <ion-icon name="person"></ion-icon>
              </a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">{% block title %} Ingreso de información de perfil del usuario {% endblock %}</li>
          </ol>
        </nav>
      </div>

    </div>

    <h6 class="text-uppercase">Proceso de Inscripción para el uso del sistema de gestión de fomento y actividades culturales en espacios públicos.</h6>
    <hr>
  <div id="stepper1" class="bs-stepper">
    <div class="card">
      
      <div class="card-header">
        <div class="d-lg-flex flex-lg-row align-items-lg-center justify-content-lg-between" role="tablist">
          <div class="step" data-target="#test-nl-1">
          <div class="step-trigger" role="tab" id="stepper1trigger1" aria-controls="test-nl-1">
            <div class="bs-stepper-circle"><i class='bx bx-user fs-4'></i></div>
            <div class="">
              <h5 class="mb-0 steper-title">Perfil de usuario</h5>
              <p class="mb-0 steper-sub-title">Información de Perfil </p>
            </div>
          </div>
          </div>
          <div class="bs-stepper-line"></div>
          <div class="step" data-target="#test-nl-2">
            <div class="step-trigger" role="tab" id="stepper2trigger2" aria-controls="test-nl-2">
            <div class="bs-stepper-circle"><ion-icon name="paper-plane-outline"></ion-icon></div>
            <div class="">
              <h5 class="mb-0 steper-title">Contacto de usuario</h5>
              <p class="mb-0 steper-sub-title">Información de contacto </p>
            </div>
            </div>
          </div>
          <div class="bs-stepper-line"></div>
          <div class="step" data-target="#test-nl-3">
            <div class="step-trigger" role="tab" id="stepper2trigger3" aria-controls="test-nl-3">
            <div class="bs-stepper-circle"><i class='bx bxs-graduation fs-4'></i></div>
            <div class="">
              <h5 class="mb-0 steper-title">Personería Jurídica</h5>
              <p class="mb-0 steper-sub-title">Información de personería jurídica</p>
            </div>
            </div>
          </div>
          <div class="bs-stepper-line"></div>
            <div class="step" data-target="#test-nl-4">
              <div class="step-trigger" role="tab" id="stepper2trigger4" aria-controls="test-nl-4">
              <div class="bs-stepper-circle"><i class='bx bx-play fs-4'></i></div>
              <div class="">
                <h5 class="mb-0 steper-title">Actividad Cultural</h5>
                <p class="mb-0 steper-sub-title">Información actividad cultural</p>
              </div>
              </div>
            </div>
        </div>
      </div>
      
      <div class="card-body">
      
      <div class="bs-stepper-content">
     

        <form action="."  method="post" enctype="multipart/form-data">
          <div id="test-l-1" role="tabpanel" aria-labelledby="stepper1trigger1">
          <div class="row g-3">
            <div class="col-12 col-lg-6">

              {% for field in profile_form.visible_fields %}
              {% if field.name == 'activity' %}
                <label for="{{ field.id }}" class="form-label">{{ field.label_tag }}</label>
                {% if field.errors %}
                  {% render_field field class="form-control " %}
                  {% for error in field.errors %}
                    <div class="invalid-feedback">
                      {{ error }}
                    </div>
                  {% endfor %}
                {% else %}
                  {% render_field field class="form-control" %}
                {% endif %}
                {% if field.help_text %}
                  <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
              {% endif %}
            {% endfor %}


              {% for field in profile_form.visible_fields %}
              {% if field.name == 'photo' %}
                <label for="{{ field.id }}" class="form-label">Foto de Perfil</label>
                {% if field.errors %}
                  {% render_field field class="form-control" %}
                  {% for error in field.errors %}
                    <div class="invalid-feedback">
                      {{ error }}
                    </div>
                  {% endfor %}
                {% else %}
                  {% render_field field class="form-control"  %}
                {% endif %}
                {% if field.help_text %}
                  <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
              {% endif %}
            {% endfor %}
            
              {% for field in user_form.visible_fields %}
                {% if field.name == 'first_name' %}
                  <label for="{{ field.id }}" class="form-label">{{ field.label_tag }}</label>
                  {% if field.errors %}
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                      <div class="invalid-feedback">
                        {{ error }}
                      </div>
                    {% endfor %}
                  {% else %}
                    {% render_field field class="form-control" %}
                  {% endif %}
                  {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                  {% endif %}
                {% endif %}
              {% endfor %}



              
          
              {% for field in user_form.visible_fields %}
                {% if field.name == 'last_name' %}
                  <label for="{{ field.id }}" class="form-label">Apellidos</label>
                  {% if field.errors %}
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                      <div class="invalid-feedback">
                        {{ error }}
                      </div>
                    {% endfor %}
                  {% else %}
                    {% render_field field class="form-control" %}
                  {% endif %}
                  {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                  {% endif %}
                {% endif %}
              {% endfor %}

 
              {% for field in user_form.visible_fields %}
                {% if field.name == 'email' %}
                  <label for="{{ field.id }}" class="form-label">Correo Electrónico</label>
                  {% if field.errors %}
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                      <div class="invalid-feedback">
                        {{ error }}
                      </div>
                    {% endfor %}
                  {% else %}
                    {% render_field field class="form-control" %}
                  {% endif %}
                  {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                  {% endif %}
                {% endif %}
              {% endfor %}
            </div>

            <div class="col-12 col-lg-6">
              
              
              {% for field in profile_form.visible_fields %}
              {% if field.name == 'date_of_birth' %}
                  <label for="{{ field.id }}" class="form-label">Fecha de Nacimiento</label>
                  {% if field.errors %}
                      {% render_field field class="form-control datepicker"  %}
                      {% for error in field.errors %}
                          <div class="invalid-feedback">
                              {{ error }}
                          </div>
                      {% endfor %}
                  {% else %}
                      {% render_field field class="form-control datepicker"  %}
                  {% endif %}
                  {% if field.help_text %}
                      <small class="form-text text-muted">{{ field.help_text }}</small>
                  {% endif %}
              {% endif %}
          {% endfor %}


            

             
                {% for field in profile_form.visible_fields %}
                  {% if field.name == 'nacionalidad' %}
                    <label for="{{ field.id }}" class="form-label">Nacionalidad</label>
                    {% if field.errors %}
                      {% render_field field class="form-control" %}
                      {% for error in field.errors %}
                        <div class="invalid-feedback">
                          {{ error }}
                        </div>
                      {% endfor %}
                    {% else %}
                      {% render_field field class="form-control" %}
                    {% endif %}
                    {% if field.help_text %}
                      <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                  {% endif %}
                {% endfor %}

             
                  {% for field in profile_form.visible_fields %}
                    {% if field.name == 'autoidentificacion' %}
                      <label for="{{ field.id }}" class="form-label">Autoidentificacion</label>
                      {% if field.errors %}
                        {% render_field field class="form-control" %}
                        {% for error in field.errors %}
                          <div class="invalid-feedback">
                            {{ error }}
                          </div>
                        {% endfor %}
                      {% else %}
                        {% render_field field class="form-control " %}
                      {% endif %}
                      {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                      {% endif %}
                    {% endif %}
                  {% endfor %}

                 <div></div>
                    {% for field in profile_form.visible_fields %}
                      {% if field.name == 'genero' %}
                        <label for="{{ field.id }}" class="form-label">Genero</label>
                        {% if field.errors %}
                          {% render_field field class="form-control" %}
                          {% for error in field.errors %}
                            <div class="invalid-feedback">
                              {{ error }}
                            </div>
                          {% endfor %}
                        {% else %}
                          {% render_field field class="form-control " %}
                        {% endif %}
                        {% if field.help_text %}
                          <small class="form-text text-muted">{{ field.help_text }}</small>
                        {% endif %}
                      {% endif %}
                    {% endfor %}
              
          
          
            
            </div>
            {% csrf_token %}
            
            <div class="col-12">
              <div class="d-flex align-items-center gap-3">
                <button class="btn btn-secondary px-4"  type="submit" value="Save changes"><i class='bx bx-save me-2'></i>Guardar</button>
                <a href ="{% url 'usuarios:edit_contact1' %}" class="btn btn-primary px-4" ><i class='bx bx-right-arrow-alt me-2'></i>Siguiente</a>
               
              </div>
            </div>
          </div>
          </div>
          </div>
        </form>
      </div>
       
      </div>
     </div>
  </div>


    
  </div>



  <script>
    $(document).ready(function () {
        $('.datepicker').datepicker({
            format: 'dd/mm/yyyy',  // Formato de fecha día/mes/año
            autoclose: true,
            language: 'es',  // Establece el idioma en español
            todayHighlight: true,
        });
    });
</script>

  
{% endblock %}

<form method="post">{% csrf_token %}
  {% bootstrap_form profile_form %}
  <input type="submit" value="Save">
</form>

<h1>Edit your account</h1>
  <p>You can edit your account using the following form:</p>
  <form action="." method="post" enctype="multipart/form-data">
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Save changes"></p>
  </form>